#!/usr/bin/env ruby
require File.expand_path('../../config/boot',  __FILE__)
require RAILS_ROOT + '/config/environment'

tag = ARGV[0]
if tag.nil?
  puts "Server tag is no set. Usage: ruby script/set_tag_to_servers newtag"
  exit
end

bind_dn = "uid=admin,o=puavo"
print "uid=admin,o=puavo password: "
system('stty','-echo');
password = STDIN.gets.chomp
system('stty','echo');
puts

ldap_bases = []

ldap_host = YAML.load_file("#{RAILS_ROOT}/config/ldap.yml")["production"]["host"]

organisations = YAML.load_file("#{RAILS_ROOT}/config/organisations.yml")

organisations.keys.each do |org|
  ldap_bases.push organisations[org]["ldap_base"]
end

I18n.locale = :en

default_ldap_configuration = ActiveLdap::Base.ensure_configuration

ldap_bases.each do |ldap_base|
  puts ldap_base
  # Setting up ldap configuration
  LdapBase.ldap_setup_connection( ldap_host,
                                  ldap_base,
                                  bind_dn,
                                  password )
  
  servers = Server.all
  
  if servers.count == 0
    puts "\tNo servers"
    puts
    next
  end

  servers.each do |server|
    puts "\t#{server.puavoHostname}"
    old_tags = server.puavoTag
    new_tags = server.puavoTag.split(" ") + [tag]
    puts "\t\told tags: " + old_tags.inspect
    puts "\t\tnew tags: " + new_tags.inspect
    server.puavoTag = new_tags
    server.save!
  end
  puts
end
