source 'http://rubygems.org'

# gems shared with puavo-rest
gem "rails", "5.2.8.1"
gem "sprockets"
gem "sqlite3"
gem "prawn"
gem "net-ldap"
gem "activeldap", :require => "active_ldap"
gem "rmagick"
gem "uuid"
gem "nokogiri"

# puavo-web specific gems
gem "pry"
gem "unicorn"
gem "gibberish"
gem "http"
gem "json"
gem "sinatra-support", :require => "sinatra/support"
gem "jwt"
gem "jwe"
gem "sshkey"
gem "i18n-js"
gem "byebug"
gem "gettext_i18n_rails"
gem "ttfunk"
gem "gettext"
gem "redis", "5.0.5"
gem "redis-client", "0.12.0"
gem "redis-namespace"
gem "sassc-rails"
gem "jquery-rails"
gem "parse-cron"

group :test do
  gem "capybara"
  gem "colorize"
  gem "cucumber"
  gem "cucumber-rails"
  gem "greenletters"
  gem "rspec"
  gem "rspec-rails"
  gem "timecop"
  gem "webmock"
end
