#!/bin/sh


cpu_count=$(nproc)

# Load average from last minute
# http://linux.die.net/man/5/proc
load_avg=$(sed -rne 's/^([0-9\.]+) .*$/\1/p' /proc/loadavg)

domain=$(cat /etc/puavo/domain)

curl --config - \
    "http://127.0.0.1:9393/v3/hogwarts/ltsp_servers/most_idle" << EOF
--request POST
--data "cpu_count=$cpu_count&load_avg=$load_avg&domain=$domain"
--user $(cat /etc/puavo/ldap/dn):$(cat /etc/puavo/ldap/password)
EOF

