source 'http://rubygems.org'  
gem 'rails', '2.3.15'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'activeldap', '1.2.4', :require => 'active_ldap' # review monkeypatches.rb before upgrading this
gem "net-ldap", '0.2.2' # review monkeypatches.rb before upgrading this
gem 'puavo_authentication', '0.2.5'
gem 'puavo-view-helpers', '0.0.3'
gem 'json'
gem 'pg'
gem 'rmagick', :require => 'RMagick'
group :development do
	gem 'cucumber-rails'
	gem 'database_cleaner'
	gem 'capybara'
	gem 'rspec-rails', '1.3.2'
	gem 'ruby-debug'
	gem 'rspec', '1.3.0'
end
