source 'http://rubygems.org'  
gem 'rails', '2.3.8'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'activeldap', :require => 'active_ldap'
gem 'net-ldap', '0.2.2'
gem 'puavo_organisation', :require => 'puavo_organisation'
gem 'puavo_authentication', '0.0.18', :require => 'puavo_authentication'
gem 'puavo-view-helpers', '0.0.3'
gem 'json'
gem 'pg'
gem 'rmagick', :require => 'RMagick'
group :development do
	gem 'cucumber-rails'
	gem 'database_cleaner'
	gem 'capybara'
	gem 'rspec-rails', '1.3.2'
	gem 'ruby-debug'
	gem 'rspec', '1.3.0'
end
