development:
  allow_anonymous: false
  host: localhost
  base: o=Puavo
  bind_dn: uid=puavo,o=puavo
  password: admin
  method: tls

test:
  host: localhost
  base: dc=edu,dc=example,dc=org
  bind_dn: uid=puavo,o=puavo
  password: admin
  method: tls

cucumber:
  host: localhost
  base: o=Puavo
  bind_dn: uid=puavo,o=puavo
  password: admin
  method: tls

production:
  host: localhost
  base: o=Puavo
  bind_dn: uid=puavo,o=puavo
  password: admin
  method: tls
