# Add external footer links here, for example:
# links:
#  -
#    name: GitHub
#    url: https://github.com
#  -
#    name: Opinsys@GitHub
#    url: https://github.com/opinsys
# footer_info: Place here for example ©opyright info
