#!/usr/bin/env ruby

# require 'rubygems' unless ENV['NO_RUBYGEMS']

ENV["RAILS_ENV"] ||= 'test'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment") unless defined?(RAILS_ROOT)
require "colorize"

require File.expand_path(File.dirname(__FILE__) + "/../acl/data")
require File.expand_path(File.dirname(__FILE__) + "/../acl/helper")

require 'pp'

TEST_DIR = File.dirname(__FILE__) + "/../acl/test/"


if not ARGV.empty?
  ARGV.each do |file|
    puts "Loading #{ file }"
    require file
  end
else
  Dir.foreach TEST_DIR do |file|
    next if [".", ".."].include? file
    file = TEST_DIR + file
    puts "Loading #{ file }"
    require file
  end
end

LDAPTestEnv.report
