#!/bin/sh

set -eu

cpu_count=$(nproc)

# Load average from last minute
# http://linux.die.net/man/5/proc
load_avg=$(sed -rne 's/^([0-9\.]+) .*$/\1/p' /proc/loadavg)

domain=$(cat /etc/puavo/domain)

# TODO: --cacert /etc/puavo/certs/rootca.pem

# TODO: dns hackery
# dig +time=2 +tries=1 SRV _puavo-api._tcp.kehitys.opinsys.fi +search +short | awk '{ sub(/\.$/, ""); printf "%s:%s", $4, $3 }'
rest_server="http://127.0.0.1:9393"

url="$rest_server/v3/ltsp_servers/$domain"

curl --config - \
     --request PUT \
     --max-time 5 \
    $url << EOF
data="cpu_count=$cpu_count"
data="load_avg=$load_avg"
user=$(cat /etc/puavo/ldap/dn):$(cat /etc/puavo/ldap/password)
EOF

