source "http://rubygems.org"

# Some code and dependencies of puavo-web is used in puavo-rest during test
# runs (ActiveLdap models).
gem "rails", "5.2.8.1"
gem "sprockets", "3.7.2"    # last version that works with Ruby 2.3
gem "sqlite3"     # ok
gem "prawn"       # ok
gem "net-ldap"    # ok
gem "activeldap", :require => "active_ldap"
gem "rmagick"     # ok
gem "uuid"        # ok
gem "nokogiri"    # ok
gem "gettext_i18n_rails", '1.9.0'

gem "sinatra", '2.0.8.1'
gem "sinatra-contrib", '2.0.8.1'
gem "uuid"        # ok
gem "puma"        # ok
gem "rack-rewrite", '1.5.1'
gem "rack", "2.1.4"   # 2.2.x breaks some VirtualHostBase tests
gem "addressable", '2.8.1'
gem "jwt"         # ok
gem "jwe"         # ok
gem "json"        # ok
gem "gssapi", '1.3.1'
gem "sinatra-r18n", '5.0.2'
gem "pry"         # ok
gem "redis", '5.0.5'
gem "yajl-ruby", '1.4.3'
gem "colorize", '0.8.1'
gem "redis-namespace", '1.9.0'
gem "httparty"    # ok
gem "pony", '1.13.1'
gem "gibberish", '2.1.1'
gem "sinatra-support", '1.2.2', :require => "sinatra/support"
gem "redlock", '1.3.2'
gem "http"        # ok
gem "dnsruby", '1.61.9'
gem "mechanize", '2.8.5'
gem "net-ldap"    # ok
gem "byebug"      # ok
gem "ntlm-http", '0.1.1'
gem "ttfunk", '1.7.0'
gem "gettext", '3.4.3'
gem "r18n-core", '5.0.1'

group :test do
  gem "shotgun", '0.9.2'
  gem "timecop", '0.9.5'
  gem "webmock", '3.18.1'
  gem "m", '1.6.0'
  gem "minitest", '5.16.3'
  gem "yard", '0.9.28'
end
