source "http://rubygems.org"

# Some code and dependencies of puavo-web is used in puavo-rest during test
# runs (ActiveLdap models).
gem "rails", '7.2.3'
gem "sprockets"
gem "sqlite3"
gem "prawn"
gem "net-ldap"
gem "activeldap", :require => "active_ldap"
gem "rmagick"
gem "nokogiri"
gem "gettext_i18n_rails"
gem 'concurrent-ruby'
gem 'sprockets-rails'

gem "sinatra"
gem "sinatra-contrib"
gem "puma"
gem "rack-rewrite"
gem "rack", "2.2.10"
gem "addressable"
gem "jwt"
gem "jwe"
gem "json"
gem "gssapi"
gem "sinatra-r18n"
gem "pry"
gem "redis"
gem "redis-client"
gem "yajl-ruby"
gem "colorize"
gem "redis-namespace"
gem "httparty"
gem "pony"
gem "gibberish"
gem "sinatra-support", :require => "sinatra/support"
gem "redlock", "1.3.2"
gem "http"
gem "dnsruby"
gem "mechanize"
gem "net-ldap"
gem "byebug"
gem "ttfunk"
gem "gettext"
gem "r18n-core"
gem "matrix"
gem 'pg'
gem 'argon2'

group :test do
  gem "shotgun"
  gem "timecop"
  gem "webmock"
  gem "m"
  gem "minitest"
  gem "yard"
end
