source "http://rubygems.org"

# Some code and dependencies of puavo-web is used in puavo-rest during test
# runs (ActiveLdap models).
gem "rails", "5.2.8.1"
gem "sprockets", "3.7.2"
gem "sqlite3"     # ok
gem "prawn"       # ok
gem "net-ldap"    # ok
gem "activeldap", :require => "active_ldap"
gem "rmagick"     # ok
gem "uuid"        # ok
gem "nokogiri"    # ok
gem "gettext_i18n_rails" # ok

gem "sinatra"     # ok
gem "sinatra-contrib" # ok
gem "uuid"        # ok
gem "puma"        # ok
gem "rack-rewrite" # ok
gem "rack", "2.1.4"   # 2.2.x breaks some VirtualHostBase tests
gem "addressable" # ok
gem "jwt"         # ok
gem "jwe"         # ok
gem "json"        # ok
gem "gssapi"      # ok
gem "sinatra-r18n" #ok
gem "pry"         # ok
gem "redis"       # ok
gem "yajl-ruby"   # ok
gem "colorize"    # ok
gem "redis-namespace" # ok
gem "httparty"    # ok
gem "pony"        # ok
gem "gibberish"   # ok
gem "sinatra-support", :require => "sinatra/support"
gem "redlock"     # ok
gem "http"        # ok
gem "dnsruby"     # ok
gem "mechanize"   # ok
gem "net-ldap"    # ok
gem "byebug"      # ok
gem "ntlm-http"   # ok
gem "ttfunk"      # ok
gem "gettext"     # ok
gem "r18n-core"   # ok

group :test do
  gem "shotgun"   # ok
  gem "timecop"   # ok
  gem "webmock"   # ok
  gem "m"         # ok
  gem "minitest"  # ok
  gem "yard"      # ok
end
