require "ldap"
require "json"
require "multi_json"
require "sinatra/base"
require "sinatra/json"
require "base64"
require "gssapi"
require "gssapi/lib_gssapi"
if Sinatra::Base.development? || ENV["DEBUG"]
  require "debugger"
  require "pry"
end

require_relative "./config"
require_relative "./auth"
require_relative "./lib/ldap_converters"
require_relative "./ldap_hash"
require_relative "./ldap_sinatra"
require_relative "./resources/users"
require_relative "./resources/schools"
require_relative "./resources/organisations"
require_relative "./resources/printer_queues"
require_relative "./resources/sso"
require_relative "./resources/ltsp_servers"
require_relative "./resources/sessions"
require_relative "./resources/wlan_networks"
require_relative "./resources/external_files"
require_relative "./resources/devices"
